### ISSUE TITLE
it can not be closed

### ISSUE THREAD

**Issue by WitekS** [rsmalc/laravel-noty#2]
you can not close the notification of any errors in the console you can not see
when I attach the sample JS code directly to the view, this notification works correctly, it can be closed with a click and the animation works properly
below the JS code that works when placed in the scrypt tags directly in the view
`<script>

        new Noty({
          type: 'success',
          text: 'Some notification text',

        }).show();

        </script>`

**Comment by navotera** [comment]
yeah unfortunately it cannot be closed... :D

**Comment by rsmalc** [comment]
Can you provide me your Laravel version and Noty version and also in which browser did this happen? I need to replace it and then can fix it.

I used it in every project without this problem.

**Comment by wody** [comment]
same here, Noty directely in console is working fine.

That's Laravel 5.6, Noty 3.2.0-beta and every current browser (FF, Chrome tested).
No JS-Error though.

**Comment by wody** [comment]
The Problem is the animation in laravel-noty.php

Changing that to the currect noty "default" values made it work for me:

```
'animation' => [
       'open' => 'noty_effects_open',
       'close' => 'noty_effects_close',
]
``` 

I just realized you already changed that in the 2.0.0 branch - perhaps you should merge that into master and release a new version.

**Comment by wody** [comment]
i fixed a bug with mismatching position / layout mappings in message.blade.php in PR #3
